server.port=8080
spring.application.name=centro-terapia-infantil

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=centroterapia;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=tu-password
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu-email@gmail.com
spring.mail.password=tu-app-password
